import "./style/reset.scss";
import "./style/normalize.scss";
import "./style/style-App.scss";
import "./style/style-Header.scss";
import "./style/style-Main.scss";
import "./style/style-Section.scss";
import "./style/theme-switch.scss";
import "./style/style-Footer.scss";
import "./style/BurgerMenu.scss";
